### ISSUE TITLE
Call to undefined function Webmention_Comments\Mf2\parse()

### ISSUE THREAD

**Issue by janboddez** [janboddez/webmention-comments#4]
`Call to undefined function Webmention_Comments\Mf2\parse() in .../webmention-comments/includes/class-webmention-comments.php:511`

**Comment by janboddez** [comment]
All the files are definitely there, in the vendor folder. Looks like a missing `composer dump-autoload` or so? After prefixing?

**Comment by janboddez** [comment]
Exact same code works just fine elsewhere. #hargl

**Comment by janboddez** [comment]
Works when I call just `\Mf2\parse()`, it works. ¯\_(ツ)_/¯

**Comment by janboddez** [comment]
Ditched PHP Scoper, at least till I better understand what might be going on. Just be careful when using this with other Composer-based plugins, I guess.

**Comment by pfefferle** [comment]
Doesn't it has to be `\Webmention_Comments\Mf2\parse()`?

**Comment by janboddez** [comment]
Should be, yes. I think the error message just leaves off the leading backslash. It was definitely there in the code. Still doesn't explain why the exact same code worked on one site and not on another, on the same host, PHP version, etc. I mean, I still think it was the autoloader. I may have dumped it differently or something. (I may eventually have another look into prefixing Composer packages in the future, but for now ... I think I'm the only person using this plugin anyway, so that helps. 😀)

**Comment by pfefferle** [comment]
Is the (generated) autoloader part of your packeage or do you generate it on your server?

**Comment by janboddez** [comment]
It was part of it, but I may have updated it on the server ... I only noticed one of the sites no longer working after I had reinstalled the plugin from scratch. Then again, I also copied over all of the *working* files, the autoloader included, to the other site. Still wouldn't work. At that point I just gave up and got rid of the prefixing thing. (If only WordPress and Composer would get along better ...) The good thing is I think it's quite unlikely someone has both this plugin (which is only available on GitHub) and another plugin that uses some of the same dependencies installed, so there's a fairly low chance of conflicting package versions.

**Comment by pfefferle** [comment]
perhaps a race condition, that the autoloader is triggered before the scoper...

**Comment by janboddez** [comment]
Looks like (https://github.com/humbug/php-scoper/issues/298) there's a conflict after all. We introduced scoping to avoid including a wrong version of the same library, but as a result, it seems that scoped classes that are the same version as a previously loaded class don't get included at all.
